version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./Proyecto_centro_logistico:/Proyecto_centro_logistico
      - ./back-up:/back-up
    ports:
      - "3306:3306"
